export const GAME_WIDTH = 640 // 1024
export const GAME_HEIGHT = 480 // 768

export const GRID_WIDTH = 20 //GAME_WIDTH / CELL_WIDTH
export const GRID_HEIGHT = 16 //GAME_HEIGHT / CELL_WIDTH

export const CELL_WIDTH = 32 //GAME_WIDTH / GRID_WIDTH
export const CELL_HEIGHT = 24 

export const LEVEL_HEIGHT = GRID_HEIGHT * CELL_HEIGHT 
export const HEADER_FOOTER_HEIGHT = (GAME_HEIGHT - LEVEL_HEIGHT) / 2